linters-settings:
 govet:
   check-shadowing: true
 golint:
   min-confidence: 0
 gocyclo:
   min-complexity: 16
 maligned:
   suggest-new: true
 dupl:
   threshold: 200
 goconst:
   min-len: 2
   min-occurrences: 2
 misspell:
   locale: US
 lll:
   line-length: 140
 gocritic:
   enabled-tags:
     - performance
     - style
     - experimental
   disabled-checks:
     - wrapperFunc
     - hugeParam
     - rangeValCopy

linters:
 disable-all: true
 enable:
   - deadcode
   - dupl
   - gas
   - gocritic
   - gocyclo
   - golint
   - gosimple
   - govet
   - ineffassign
   - maligned
   - megacheck
   - misspell
   - nakedret
   - prealloc
   - scopelint
   - structcheck
   - stylecheck
   - typecheck
   - unconvert
   - unparam
   - varcheck
 fast: false

run:
 skip-dirs:
   - vendor
 concurrency: 4

issues:
 exclude-rules:
   - text: "weak cryptographic primitive"
     linters:
       - gosec
 exclude-use-default: false

service:
 golangci-lint-version: 1.51.2
