ARG GO_VERSION
FROM golang:$GO_VERSION-alpine3.10 as builder
RUN apk add --no-cache make=4.2.1-r2 gcc=8.3.0-r0 libc-dev=0.7.1-r0 git=2.22.0-r0
WORKDIR /go/src/github.com/optimizely/sidedoor
COPY . .
RUN make build

FROM alpine:3.10
RUN apk add --no-cache ca-certificates=20190108-r0
COPY --from=builder /go/src/github.com/optimizely/sidedoor/bin/sidedoor /sidedoor
CMD ["/sidedoor"]
