ARG GO_VERSION
FROM golang:$GO_VERSION as builder
RUN  addgroup agentgroup
RUN useradd -u 10001 agentuser -g agentgroup

WORKDIR /go/src/github.com/optimizely/agent
COPY . .
RUN make setup build
RUN make ci_build_static_binary

FROM scratch
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /go/src/github.com/optimizely/agent/bin/optimizely /optimizely
COPY --from=builder /etc/passwd /etc/passwd
USER agentuser
CMD ["/optimizely"]

