FROM golang:1.13

WORKDIR /go/src/github.com/optimizely/sidedoor
COPY . .
RUN make ci_build_static_binary

FROM scratch
COPY --from=0 /go/src/github.com/optimizely/sidedoor/bin/sidedoor /sidedoor
CMD ["/sidedoor"]
