FROM centos:7

RUN yum -y install ruby-devel gcc make rpm-build rubygems

RUN gem install fpm pleaserun

WORKDIR /workdir

COPY sidedoor /workdir

RUN fpm -s pleaserun -t rpm -n sidedoor_initscripts --pleaserun-name sidedoor -v 0.1.0 /usr/bin/sidedoor
RUN fpm -s dir -t rpm -n sidedoor -v 0.1.0 /workdir/app=/usr/bin/

CMD ["/bin/bash"]
