FROM ubuntu:18.04

ARG DEBIAN_FRONTEND=noninteractive
ARG APP_VERSION

RUN apt-get -y update && apt-get -y install --no-install-recommends \
      ruby=1:2.5.1 \
      ruby-dev=1:2.5.1 \
      build-essential=12.4ubuntu1 \
      && rm -rf /var/lib/apt/lists/*
RUN gem install --no-ri --no-rdoc fpm:1.11.0 pleaserun:0.0.30

WORKDIR /workdir

COPY optimizely /workdir

RUN fpm -v $APP_VERSION -s pleaserun -t dir -n optimizely /usr/bin/optimizely
RUN printf "#!/bin/sh\nsh /usr/share/pleaserun/optimizely/cleanup.sh\nrm -rf /usr/share/pleaserun/optimizely/cleanup.sh\n" > /workdir/optimizely.dir/usr/share/pleaserun/optimizely/delete.sh
RUN fpm -v $APP_VERSION -n optimizely -s dir -t deb --after-install /workdir/optimizely.dir/usr/share/pleaserun/optimizely/install.sh --before-remove /workdir/optimizely.dir/usr/share/pleaserun/optimizely/delete.sh /workdir/optimizely=/usr/bin/ /workdir/optimizely.dir/usr/share/pleaserun/=/usr/share/pleaserun

CMD ["/bin/bash"]
