apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "optimizely-agent.name" . }}-config"
  labels:
    {{- include "optimizely-agent.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.env.variables }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
  config.yaml: |
    {{- tpl .Values.config . | nindent 4 }}
