apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "optimizely-agent.name" . }}-secrets"
type: Opaque
data:
  {{- range $k, $v := .Values.env.secrets }}
  {{ $k }}: {{ $v | b64enc }}
  {{- end }}
