/*
 * Optimizely Server API
 *
 * Optimizely.
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package optlyd

type Feature struct {
	Id int32 `json:"id,enabled,omitempty"`

	Key string `json:"key"`

	Enabled bool `json:"enabled"`

	Variables map[string]string `json:"variables,omitempty"`

	Variations map[string]FeatureVariation `json:"variations,omitempty"`
}
