/*
 * Optimizely Server API
 *
 * Optimizely.
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package optlyd

type Variation struct {

	Id int32 `json:"id"`

	Key string `json:"key"`
}
