.DEFAULT_GOAL := help

ci_build_fpm_centos: ## build fpm_centos image for packaging
	docker build -f scripts/dockerfiles/Dockerfile.fpm_centos -t fpm_centos ${TRAVIS_BUILD_DIR}/bin

ci_build_fpm_ubuntu: ## build fpm_centos image for packaging
	docker build -f scripts/dockerfiles/Dockerfile.fpm_ubuntu -t fpm_ubuntu ${TRAVIS_BUILD_DIR}/bin

ci_get_fpm_centos: ## get generated rpm
	docker run -v /tmp/output_packages:/output -it fpm_centos bash -c "cp *.rpm /output"

ci_get_fpm_ubuntu: ## get generated deb
	docker run -v /tmp/output_packages:/output -it fpm_ubuntu bash -c "cp *.deb /output"

ci_install:  ## install ci dependencies
	$(GOGET) github.com/mattn/goveralls

ci_coveralls: cover ci_install ## upload coverage report to coveralls
	${GOPATH}/bin/goveralls -coverprofile=cover.out -service=travis-ci
