/*
 * Optimizely Server API
 *
 * Optimizely.
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//    sw "github.com/myname/myrepo/optlyd"
	//
	"github.com/optimizely/sidedoor/pkg/http"
)

func main() {
	log.Printf("Server started")
	router := router.NewRouter()

	log.Fatal(http.ListenAndServe(":8080", router))
}
