/*
 * Optimizely Server API
 *
 * Optimizely.
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"net/http"
	"log"

	"github.com/optimizely/sidedoor/pkg/api"
)

func main() {
	log.Printf("Server started")
	router := api.NewRouter()

	log.Fatal(http.ListenAndServe(":8080", router))
}
