# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Agent package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  acceptance-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        pip install -r ./tests/acceptance/requirements.txt 
    - name: Run acceptance tests
      run: |
        make -e setup build
        MYHOST="http://localhost:8080" make test-acceptance
